url: alcazar90.github.io
baseurl: /from_scratch
highlighter: rouge

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md	
